name: Build Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display current directory and list files
      shell: powershell
      run: |
        Get-Location
        Get-ChildItem

    - name: Build Windows
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        if (Test-Path .\build.bat) {
          Write-Host "build.bat found, executing..."
          .\build.bat --rebuild --release
        } else {
          Write-Error "build.bat not found in the current directory"
          exit 1
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: .\_build\windows-x86_64\release\
        if-no-files-found: error
