[package]
version = "1.1.0"
authors =["Pierre-Oliver Trottier <ptrottier@nvidia.com>"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["layer", "manager", "service"]
title = "Lightspeed Layer Manager Service"
description = "Expose microservices to manage layers in the stage"
icon = "data/icon.png"
category = "other"
preview_image = "data/preview.png"

[dependencies]
"lightspeed.layer_manager.core" = {}
"omni.flux.service.factory" = {}

[[python.module]]
name = "lightspeed.layer_manager.service"
